Giveaway/urls.py
from django.contrib import admin
from django.urls import path,include,register_converter
from  django.conf import settings
from django.conf.urls.static import static
from givers import views
from django.conf.urls import url
from django.views.static import serve
from django.contrib.auth import views as auth_views






urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('signup/',views.signupuser,name='signupuser'),
    path('login/',views.loginuser,name='loginuser'),
    path('logout/',views.logoutuser,name='logoutuser'),
    path('account/',views.user_account, name= 'user_account'),
    path('add/',views.creategift,name='creategift'),
    path('giveaway/',views.giveaway, name='giveaway'),
    path('gifts/<int:gift_id>/view',views.viewgift, name='viewgift'),
    path('profile/edit', views.edit_profile, name='account_update'),
    path('gifts/<int:gift_id>/delete',views.deletegift, name='deletegift'),
    path('pick/<int:gift_id>/gift',views.pickgift, name='selectgift'),
    path('view/<int:gift_id>/picked',views.viewpicked, name='viewpicked'),
    path('return/<int:gift_id>/picked',views.returnpicked, name='returnpicked'),
    path('gift/<int:gift_id>/redeem',views.redeempicked, name='redeempicked'),
    path('gift/return',views.cancelpicked, name='cancelpicked'),
    path('gift/redeem',views.redeem,name='redeemgift'),
    path('contact/',views.contact,name='contact'),
    path('about/',views.about,name='about'),
    path('blog/',include('blog.urls'),name='blog'),
    path('social-oauth/',include('social_django.urls'),name='social'),
    path('mail/',views.my_mail,name='mail'),
    path('', include('givers.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    path('accounts/', include('allauth.urls')),
]










urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from  django.conf import settings
from django.conf.urls.static import static
from blog import views
from django.conf.urls import url
from django.views.static import serve

app_name='blog'

urlpatterns = [
    path('',views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/view',views.detail, name='detail'),
    path('<int:blog_id>/',views.post_comment,name='post_comment'),
    path('all',views.list_blog,name='list_blog'),
    path ('category/<str:category>',views.category,name='category'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User,update_last_login
from django.contrib.auth.signals import user_logged_in



def update_first_login(sender,user,**kwargs):
    if user.last_login is None:
        kwargs['request'].session['first_login']=True
    update_last_login(sender,user,**kwargs)

user_logged_in.disconnect(update_last_login)
user_logged_in.connect(update_first_login)



class Blog(models.Model):
    title=models.CharField(max_length=100,unique=True)
    date=models.DateField(auto_now=True)
    image=models.ImageField(upload_to='givers/images',default='car1.jpg')
    description=models.CharField(max_length=200)
    story=models.TextField()
    genre=models.CharField(max_length=100)

    def __str__(self):
        return self.title

class Comment(models.Model):
    #user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='comments')
    post=models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='comments')
    email = models.EmailField(max_length=100)
    body= models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'comment {self.body} by {self.email}'

blog/forms.py
from .models import Comment
from django.forms import ModelForm, fields
from django import forms





class CommentForm(ModelForm):
    
    body = forms.CharField(label='',widget=forms.Textarea(attrs={
        'class':'form-control',
        'placeholder':'comment here',
        'rows':2,
        'cols':50,
    }))
    class Meta:
        model = Comment
        fields= ('email','body')

blog/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Blog,Comment
from .forms import CommentForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect,HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator





def all_blogs(request):
    blogs = Blog.objects.order_by('-id')[:12]
    genre=Blog.objects.values('genre').distinct()
    category=list(genre)
    category=[(i['genre']) for i in category]
    blog_count = Blog.objects.count
    return render(request,'blog/blog_index.html',{'blogs':blogs,'blog_count':blog_count,'category':category})


def detail(request,blog_id):
    
    posts = get_object_or_404(Blog, pk= blog_id)
    blog_desc = Blog.objects.all()
    comments = posts.comments.filter(active=True).order_by('-created')[:30]
    comment_form =CommentForm()
    return render(request,'blog/viewblog.html',{'posts':posts,'comments':comments,
                'comment_form':comment_form,'blog_desc':blog_desc})
       
def list_blog(request):
    blogs=Blog.objects.all().order_by('-date')
    p=Paginator(blogs,10)
    page_number=request.GET.get('page')
    try:
        page_obj=p.get_page(page_number)
    except PageNotAnInterger:
        page_obj=p.page(1)
    except EmptyPage:
        page_obj=p.page(p.num_pages)

    return render(request,'blog/all_blog.html',{'blogs':blogs,'page_obj':page_obj})


def post_comment(request,blog_id):
    posts= get_object_or_404(Blog,pk=blog_id)
    
    if request.method=='POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment=comment_form.save(commit=False)
            new_comment.post= posts
            new_comment.save()
        return HttpResponseRedirect('view')    
        
    else:
        comment_form= CommentForm()
        return render(request,'blog/viewblog.html',{'comment_form':comment_form})


@csrf_exempt
def category(request,category):
    cat=str(category)
    blog_count=Blog.objects.filter(genre=cat).count
    blogs=Blog.objects.filter(genre=cat)
    p=Paginator(blogs,10)
    page_number=request.GET.get('page')
    try:
        page_obj=p.get_page(page_number)
    except PageNotAnInterger:
        page_obj=p.page(1)
    except EmptyPage:
        page_obj=p.page(p.num_pages)
    return render(request,'blog/blog_genre.html',{'page_obj':page_obj,'cat':cat,'blog_count':blog_count})

blog/templates/blog/all_blog.html
{% extends 'givers/base_blog_genre.html' %} 


{% load static %}
{% block content %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Giveaway Blog</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" />
    <link rel="stylesheet" href="{% static 'givers/css/all.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'givers/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'givers/css/templatemo-style.css' %}"/>
    <link rel="stylesheet" href="{% static 'givers/css/blog.css' %}"/>
<!--
Parallo Template
https://templatemo.com/tm-534-parallo
-->
  </head>
<body>
    <div class="parallax-window" data-parallax="scroll" data-image-src="{% static 'givers/img/bg-01.jpg' %}">



{% for i in page_obj.object_list  %}
<ul>
    <li style="text-align: left;">

        <a href = "{% url 'blog:detail' i.id %}"><h4 style="color: white;">{{ i.title|upper }}</h4></a> 
        <h4 style="color: white;">{{ i.date|date:'d M Y'|upper }}</h4> 
        <p style="color: white;">{{ i.genre }}</p>
        <p style="color: white;">{{ i.story|safe|truncatechars:50 }}</p> <br>
        <hr>
    </li>
</ul>
{% endfor  %} 
<div class="row" style="padding-top: 10px;">
    <div class="col-md-5"></div>
    <div class="col-md-2" style="text-align: center;">
        {% if page_obj.object_list %}
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" style="color:white"><<</a>
        {% endif %}
        <span style="color:white">{{ page_obj.number }}</span>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" style="color:white">>></a>
        {% endif %}
        {% endif %}
    </div>
    <div class="col-md-5"></div>
</div>
    </div>
    <script src="{% static 'givers/js/jquery.min.js' %}"></script>
    <script src="{% static 'givers/js/parallax.min.js' %}"></script>
    <script src="{% static 'givers/js/bootstrap.min.js' %}"></script>
</body>
</html>
{% endblock %}

blog/templates/blog/blog_genre.html
{% extends 'givers/base_all_blog.html' %} 


{% load static %}
{% block content %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Giveaway Blog</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" />
    <link rel="stylesheet" href="{% static 'givers/css/all.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'givers/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'givers/css/templatemo-style.css' %}"/>
    <link rel="stylesheet" href="{% static 'givers/css/blog.css' %}"/>

    
<!--
Parallo Template
https://templatemo.com/tm-534-parallo
-->
  </head>
<body>
    
    <div class="parallax-window" data-parallax="scroll" data-image-src="{% static 'givers/img/blog_background.jpeg' %}">

<h2 style="color:beige;font-family: 'Times New Roman', Times, serif;text-align: center;padding-bottom: 30px;font-size: larger;"> {{ blog_count }} {{ cat }} article{{ blog_count|pluralize }} for you to enjoy </h2>

{% for i in page_obj.object_list  %}
<ul>
    <li style="text-align: left;">

        <a href = "{% url 'blog:detail' i.id %}"><h4 style="color:beige;">{{ i.title|upper }}</h4></a> 
        <h4 style="color:beige">{{ i.date|date:'d M Y'|upper }}</h4> 
        <p style="color:beige">{{ i.genre }}</p>
        <p style="color:beige">{{ i.story|safe|truncatechars:50 }}</p> <br>
        <hr>
    </li>
</ul>
{% endfor  %} 
<div class="row" style="padding-top: 10px;">
    <div class="col-md-5"></div>
    <div class="col-md-2" style="text-align: center;">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" style="color:white"><<</a>
        {% endif %}
        <span style="color:white">{{ page_obj.number }}</span>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" style="color:white">>></a>
        {% endif %}
    </div>
    <div class="col-md-5"></div>
</div>
    </div>
    <script src="{% static 'givers/js/jquery.min.js' %}"></script>
    <script src="{% static 'givers/js/parallax.min.js' %}"></script>
    <script src="{% static 'givers/js/bootstrap.min.js' %}"></script>

</body>
</html>
{% endblock %}

blog/templates/blog/blog_index.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Giveaway Blog</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" />
    <link rel="stylesheet" href="{% static 'givers/css/all.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'givers/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'givers/css/templatemo-style.css' %}"/>
    <link rel="stylesheet" href="{% static 'givers/css/blog.css' %}"/>
<!--
Parallo Template
https://templatemo.com/tm-534-parallo
-->
  </head>
  <body>
    <div class="parallax-window" data-parallax="scroll" data-image-src="{% static 'givers/img/4.jpg' %}">
      <div class="container-fluid">
        <div class="row tm-brand-row">
          <div class="col-lg-4 col-11">
            <div class="tm-brand-container tm-bg-white-transparent">
              <div class="tm-brand-texts">
                <h1 class="text-uppercase tm-brand-name">Giveaway</h1>
                <p class="small">Articles for your delight</p>
              </div>
            </div>
          </div>
          <div  class="col-lg-4 col-0"></div>
          <div class="col-lg-4 col-1">
            <h3 style="padding-bottom: 10px;color:white">Available Categories</h3>
            <ul>
              {% for i in category %}
              <li ><a id="cat" onclick="send_value()" name='category' href="{% url 'blog:category' i %}" style="color:white">{{ i }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>

        <section class="row" id="tmHome">
          <div class="col-12 tm-home-container">
            <div class="text-white tm-home-left">
              <p class="text-uppercase tm-slogan" style="color:white">We want to make your site experience interesting</p>
              <hr class="tm-home-hr" />
              <h2 class="tm-home-title" style="color: white;">We have {{ blog_count}} article{{ blog_count|pluralize }} for your reading pleasure</h2>
              <p class="tm-home-text" style="color:white">
                Reading has a way of making your mind travel, thereby bringing refreshment of mind.
              </p>
            </div>
          </div>
          {% for i in blogs  %}
          {% if forloop.counter0|divisibleby:4 %}<div class="row" >{% endif %}
            <div class="col-md-3 col-sm-6" style="color:white">
            <div class="card" style="width: 18rem;padding-top: 20px;">
              <img class="card-img-top" src="{{ i.image.url }}" alt="Card image cap" height=250 width=250 style="border-radius: 10px;">
              <div class="card-body">
                <h5 class="card-title" style="color: white;font-size:larger;"><b>{{ i.title|upper }}</b> <span style="padding-left: 10px;">{{ i.date|timesince }}</span></h5>
                <p class="card-text">{{ i.story|safe|truncatechars:100 }}</p>
                <a href="{% url 'blog:detail' i.id %}" class="btn btn-primary">Read More</a>
              </div>
            </div>
          </div>
          {% if forloop.counter|divisibleby:4 or forloop.last %}</div>{% endif %}
        {% endfor %}

        </section>
        <div class="row" style="padding-top: 20px;">
          <div class="col-md-11"></div>
          <div class="col-md-1">
            <a href="{% url 'blog:list_blog'  %}" style="color: white;">view all</a>
          </div>
          <div style="padding-bottom: 70px;"></div>
        </div>

        

        
      </div>
      <!-- .container-fluid -->
    </div>
    
    <script src="{% static 'givers/js/jquery.min.js' %}"></script>
    <script src="{% static 'givers/js/parallax.min.js' %}"></script>
    <script src="{% static 'givers/js/bootstrap.min.js' %}"></script>
    <script>
      function send_value(){
        $.ajax({
          url:'/category/',
          method:'POST',
          data:{quantity: $('#cat').val()},

        });
      }
    </script>
  </body>
</html>

blog/templates/blog/viewblog.html
{% extends 'givers/base_dashboard.html' %} 

{% load crispy_forms_tags %}
{% load static %}

{% block content %}



<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Giveaway Blog</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" />
    <link rel="stylesheet" href="{% static 'givers/css/all.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'givers/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'givers/css/templatemo-style.css' %}"/>
    <link rel="stylesheet" href="{% static 'givers/css/blog.css' %}"/>
<!--
Parallo Template
https://templatemo.com/tm-534-parallo
-->
  </head>

<body>
    <div class="parallax-window" data-parallax="scroll" data-image-src="{% static 'givers/img/city1.jpg' %}">
<div style="padding-top: 60px;">
<h3 style="color: white;font-size: larger;">{{ posts.title }}</h3>
<h4 style="color:white"> {{ posts.genre }}</h4>
<h5 style="color:white">---{{   posts.date|date:'F jS Y'|upper }}---</h5>
</div>
<hr>
<div class="container-fluid">
<div class="row">
    <textarea readonly  class="blog" style="border: turquoise 2px solid;overflow: auto;background-color: rgb(211, 215, 219);border-radius:12px ;" >{{ posts.story|safe }}</textarea>
</div>
    <div class="row">
        <div class="col-sm-9 col-md-10 col-lg-11"></div>
        <div class="col-sm-3 col-md-2 col-lg-1"><button style="border-radius: 12px 30px;background-color: mediumspringgreen;text-align: center;font-family: fantasy;font-size: 0.85rem;" id="btn-appear">comment</button></div>
    </div>
    
    <div class="row">
        <div class="col-sm-6 col-md-7 col-lg-8">{{ error }}</div>
        <div class="col-sm-6 col-md-5 col-lg-4">
            <form  method="post" id = "comment-form" action="{% url 'blog:post_comment' posts.id %}">
                 {% csrf_token %}
                <table>
                {{ comment_form | crispy }}
                </table>
                <button class="button button1" id='btn-disappear'  type='submit'>submit</button>
            </form>
        </div>
        <hr>
        {% for i in comments %}
        {% if forloop.counter0|divisibleby:3 %}<div class="row">{% endif %}
        <div class="col-sm-6 col-md-4">
            <b style="color:rgb(241, 167, 55);">{{  i.email }}</b> <span style="padding-left: 10px;"></span> <b style="color:rgb(241, 167, 55);">{{ i.created|timesince }} ago</b>
            <p style="color:rgb(241, 167, 55)">{{ i.body }}</p>
            <hr>
        </div>
        {% if forloop.counter|divisibleby:3 or forloop.last %}</div>{% endif %}
{% endfor %}
    
    </div>
    
</div>
    </div>







    <script src="{% static 'givers/js/jquery.min.js' %}"></script>
    <script src="{% static 'givers/js/parallax.min.js' %}"></script>
    <script src="{% static 'givers/js/bootstrap.min.js' %}"></script>
    <script>
        const form = document.querySelector('#comment-form');
        const btn_appear = document.querySelector('#btn-appear');
        const btn_disappear =document.getElementById('btn-disappear');
        btn_appear.addEventListener('click',formAppear);
        btn_disappear.addEventListener('click',formDisappear);
        function formAppear(){
            form.style.display = 'block';
        }
        function formDisappear(){
            form.style.display = 'none';
        }
    </script>
</body>
</html>
{% endblock %}