Giveaway/urls.py
from django.contrib import admin
from django.urls import path,include,register_converter
from  django.conf import settings
from django.conf.urls.static import static
from givers import views
from django.conf.urls import url
from django.views.static import serve
from django.contrib.auth import views as auth_views






urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('signup/',views.signupuser,name='signupuser'),
    path('login/',views.loginuser,name='loginuser'),
    path('logout/',views.logoutuser,name='logoutuser'),
    path('account/',views.user_account, name= 'user_account'),
    path('add/',views.creategift,name='creategift'),
    path('giveaway/',views.giveaway, name='giveaway'),
    path('gifts/<int:gift_id>/view',views.viewgift, name='viewgift'),
    path('profile/edit', views.edit_profile, name='account_update'),
    path('gifts/<int:gift_id>/delete',views.deletegift, name='deletegift'),
    path('pick/<int:gift_id>/gift',views.pickgift, name='selectgift'),
    path('view/<int:gift_id>/picked',views.viewpicked, name='viewpicked'),
    path('return/<int:gift_id>/picked',views.returnpicked, name='returnpicked'),
    path('gift/<int:gift_id>/redeem',views.redeempicked, name='redeempicked'),
    path('gift/return',views.cancelpicked, name='cancelpicked'),
    path('gift/redeem',views.redeem,name='redeemgift'),
    path('contact/',views.contact,name='contact'),
    path('about/',views.about,name='about'),
    path('blog/',include('blog.urls'),name='blog'),
    path('social-oauth/',include('social_django.urls'),name='social'),
    path('mail/',views.my_mail,name='mail'),
    path('', include('givers.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    path('accounts/', include('allauth.urls')),
]










urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from  django.conf import settings
from django.conf.urls.static import static
from blog import views
from django.conf.urls import url
from django.views.static import serve

app_name='blog'

urlpatterns = [
    path('',views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/view',views.detail, name='detail'),
    path('<int:blog_id>/',views.post_comment,name='post_comment'),
    path('all',views.list_blog,name='list_blog'),
    path ('category/<str:category>',views.category,name='category'),
]

givers/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("password_reset/", views.password_reset_request, name="password_reset"),
]

givers/forms.py
from django.db import models
from django.forms.models import ALL_FIELDS
from .models import Give,Profile,ContactUs,states,Vendor
from django.forms import ModelForm, fields
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import validate_num



class ContactUsForm(ModelForm):
    
    class Meta:
        model= ContactUs
        fields = ('email','subject','ticket','body')


class GiveForm(ModelForm):
    
    class Meta:
        model= Give
        fields = ('name','category','description','image','quantity','state','giver_number','address')
    
class SignupForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password Again'}))
    email = forms.EmailField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Email'}))
    firstname = forms.CharField(max_length= 100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}))
    lastname = forms.CharField(max_length= 100,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}))
    username = forms.CharField(max_length= 200,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}))
    phone_number=forms.IntegerField(required=True)
    class Meta:
        model = User
        fields = ('firstname','lastname','username','email','phone_number','password1','password2')

class Profileform(ModelForm):
    
    firstname = forms.CharField(max_length= 100)
    lastname = forms.CharField(max_length= 100)
    email = forms.EmailField(max_length=100)
    phone_number=forms.IntegerField(required=True)
    class Meta:
        model = Profile
        fields = ('profile_pic','firstname','lastname','email','sex','state','phone_number','bio')

class VendorForm(GiveForm):
    state=forms.ChoiceField(widget=forms.Select(attrs={'placeholder':'State of Residence'}),choices=states)
        
    class Meta:
        model = Vendor
        fields=('receiver_number','state','delivery_address')

givers/views.py
from os import times
from typing import NewType
from django.forms import utils
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.db import IntegrityError
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .forms import SignupForm,GiveForm,ContactUsForm,Profileform,VendorForm
from .models import Profile,Give,ContactUs,Vendor
from django.http import HttpResponseRedirect,HttpResponse
import random
from django.contrib import messages
import os
from Giveaway.settings import STATIC_ROOT
from django.db.models import Sum
from time import sleep
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.mail import send_mail,BadHeaderError
from django.conf import settings
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.core.mail import EmailMultiAlternatives
from django import template
from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
import requests 
from .decorators import check_recaptcha


UserModel = get_user_model()



def home(request):
    return render(request,'givers/home.html')

def about(request):
    return render(request,'givers/about.html')

def signupuser(request):
    
    if request.method == 'POST':
        form = SignupForm()
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if password1 == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request,'Username Already Taken')
                return redirect('signupuser')
                
            elif User.objects.filter(email=email).exists():
                messages.error(request,'Email Already Exist')
                return redirect('signupuser')
                
            else:
                form = SignupForm(request.POST)
                if form.is_valid():
                    user = form.save()
                    user.refresh_from_db()
                    user.profile.firstname=form.cleaned_data.get('firstname')
                    user.profile.lastname=form.cleaned_data.get('lastname')
                    user.profile.email=form.cleaned_data.get('email')
                    user.profile.phone_number=  form.cleaned_data.get('phone_number')
                    if not len(str(user.profile.phone_number)) == 10:
                        messages.error(request,'invalid phone number')
                        return redirect('signupuser')
                    user.save()
                    current_site = get_current_site(request)
                    subject = 'Activate your account.'
                    plaintext = template.loader.get_template('password/acc_activate_email.txt')
                    htmltemp = template.loader.get_template('password/acc_activate_email.html')
                    c = { 
					"email":user.profile.email,
					'domain':'127.0.0.1:8000',
					'site_name': 'Giveawaynow',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user": user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
                    text_content = plaintext.render(c)
                    html_content = htmltemp.render(c)
                    try:
                        msg = EmailMultiAlternatives(subject, text_content, 'Giveaway <admin@example.com>', [user.profile.email], headers = {'Reply-To': 'admin@example.com'})
                        msg.attach_alternative(html_content, "text/html")
                        msg.send()
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    messages.info(request, "A verification mail has been sent to your email, kindly complete registration from there. ")
                    return redirect ("home")
                    '''username = form.cleaned_data.get('username')
                    password = form.cleaned_data.get('password1')
                    user= authenticate(username=username,password=password)
                    login(request,user)
                    return redirect('account_update')'''
                else:
                    form = SignupForm()
                    messages.error(request,'form is invalid')
                    return redirect('signupuser')
                    
        else:
            messages.error(request,'Password does not match')
            return redirect('signupuser')
            
    else:
        form = SignupForm()
        return render(request, 'givers/signupuser.html',{'form':form})


def contact(request):
    
    if request.method=='POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Thanks, we will treat as urgent')
            return redirect('contact')
    else:
        form=ContactUsForm()
        return render(request,'givers/contact.html',{'form':form})


@login_required(login_url='/login/')
def user_account(request):
    user = request.user
    give=Give.objects.filter(gift_recipient=request.user.username,gift_status='redeemed')
    if len(give)==0:
        amount=''
    else:
        amt=[]
        for i in give:
            if i.gift.payment_status == False:
                if i.gift.amount is not None:
                    amt.append(i.gift.amount)
        if sum(amt)==0:
            amount=''
        else:
            amount=sum(amt,2000)
            
    all_gift = Give.objects.filter(user=user).count
    picks= Give.objects.filter(gift_recipient=user,date_requested__isnull=False)
    pick_count= Give.objects.filter(gift_recipient=user,date_requested__isnull=False).count
    gifts = Give.objects.filter(user=user, date_requested__isnull = True)
    mis_count = Give.objects.filter(user=user, date_requested__isnull = True).count
    return render(request,'givers/user_account.html',{'gifts':gifts,'user':user,'mis_count':mis_count,'picks':picks,'pick_count':pick_count,'all_gift':all_gift,'form':VendorForm(),'amount':amount})

@login_required(login_url='/login/')
def logoutuser(request):
    logout(request)
    return redirect('home')



'''def loginuser(request):
    if request.method == 'GET':
        return render(request, 'givers/loginuser.html', {'form':AuthenticationForm()})
    else:
        user= authenticate(request, username=request.POST['username'],password=request.POST['password']) 
        if user is None:
             return render(request, 'givers/loginuser.html', {'form':AuthenticationForm(),'error':'Username or Password incorrect'})
        else:
            login(request,user)
            if request.session.get('first_login'):
                return redirect('account_update')
            return redirect('user_account')'''


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'givers/loginuser.html', {'form':AuthenticationForm(),'recaptcha_site_key':settings.GOOGLE_RECAPTCHA_SITE_KEY})
    else:
        user= authenticate(request, username=request.POST['username'],password=request.POST['password']) 
        if user is None:
            messages.error(request,'Username or Password Incorrect')
            return redirect('loginuser')
            
        else:
            
            recaptcha_response = request.POST.get('g-recaptcha-response')
            print(recaptcha_response)
            data = {
			'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
			'response': recaptcha_response,
			}
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            result = r.json()
            print(result)
            if result['success']:
                login(request,user)
                if request.session.get('first_login'):
                    return redirect('account_update')
                return redirect('user_account')
            messages.error(request, 'Invalid reCAPTCHA. Please try again.')
            return redirect('loginuser')


@login_required(login_url='/login/')
def creategift(request):
    if request.method == 'GET':
        return render(request, 'givers/creategiving.html', {'form':GiveForm()})
    else:
        form = GiveForm(request.POST,request.FILES)
        if form.is_valid():
            new_gift = form.save(commit = False)
            new_gift.user = request.user
            new_gift.save()
            new_gift.gift.name = form.cleaned_data.get('name')
            new_gift.gift.category = form.cleaned_data.get('category')
            new_gift.gift.image = form.cleaned_data.get('image')
            new_gift.gift.giver_number = form.cleaned_data.get('giver_number')
            new_gift.gift.address = form.cleaned_data.get('address')
            if not len(str(new_gift.gift.giver_number)) == 10:
                        messages.error(request,'invalid phone number')
                        return redirect('creategift')
            new_gift.save()
            return redirect('giveaway')
        else:
            return render(request,'givers/creategiving.html',{'form':form,'error':'something went wrong'})

@login_required(login_url='/login/')
def giveaway(request):
    
    user=request.user
    gift1= Give.objects.filter(date_requested__isnull=True)
    query = request.GET.get('q')
    gifts= Give.objects.filter(Q(date_requested__isnull = True)&Q(state=user.profile.state)).order_by('-date_posted')
    if query:

givers/templates/givers/about.html
{% extends 'givers/base.html' %}



{% block content %}
<div class="content-wrapper">
                
    <!-- ABOUT -->
    <div class="page-section" id="about">
    <div class="row">
        <div class="col-md-12">
            <h4 class="widget-title">Learn About Us</h4>
            <div class="about-image">
                <img src="{% static 'givers/img/8.jpg' %}" alt="about me">
            </div>
            <p>Volton is free website design from <span class="blue">template</span><span class="green">mo</span>. You can use this template for any purpose. Please tell your friends about it. Thank you. Credit goes to <a rel="nofollow" href="http://unsplash.com" target="_parent">Unsplash</a> for images used in this design. You can <strong>change menu icons</strong> by checking <a rel="nofollow" href="http://fontawesome.info/font-awesome-icon-world-map/" target="_parent">Font Awesome</a> (version 4). Example: <strong>&lt;i class=&quot;fa fa-camera&quot;&gt;&lt;/i&gt;</strong></p>
            <hr>
        </div>
    </div> <!-- #about -->
    </div>

</div>









{% endblock %}

givers/templates/givers/account_update.html
{% extends 'givers/index.html' %}

{%  block content %}


{% load crispy_forms_tags %}

<div class="account">

<h2 style="padding-left: 20px;">kindly update your account {{ user.username }}</h2>
<br>
<p style="padding-left: 20px;">{{ error }}</p>
<div class="row d-flex justify-content-center">
    <a href="{% url 'password_reset' %}">Change Password?</a>
</div>
<div class="row d-flex justify-content-center">
    <form class="form-width" enctype="multipart/form-data"  style="max-width: 18rem;border:slategray 2px solid;padding: 50px;border-radius: 15px;background-color: white;"  method="POST" action="{% url 'account_update' %}">
    {% csrf_token %}
        <table>
        {{ profile_form | crispy }}
        </table>
        <button class="button button1"  type="submit">Update</button>
    </form>
</div>




{% endblock %}

givers/templates/givers/base_all_blog.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600"/>
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/>
<link rel="stylesheet" href="{% static 'givers/css/base.css' %}"/>
<link rel="icon" type="image/jpg"  href="{% static 'givers/img/car1.jpg' %}"/>
<title>Giveaway</title>
<style>
 
body {
  font-family: "Lato", sans-serif;
}

.sidebar {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color:rgb(27, 14, 5);
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidebar a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 15px;
  color: beige;
  display: block;
  transition: 0.3s;
}

.sidebar a:hover {
  color:turquoise;
}

.sidebar .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 25px;
  margin-left: 50px;
}

.openbtn {
  font-size: 20px;
  cursor: pointer;
  background-color:rgb(37, 20, 8);
  color: white;
  padding: 10px 15px;
  border: none;
}

.openbtn:hover {
  background-color:teal;
}

#main {
  transition: margin-left .5s;
  padding: 16px;
}

/* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
@media screen and (max-height: 450px) {
  .sidebar {padding-top: 15px;}
  .sidebar a {font-size: 18px;}
}
</style>
</head>
<body>

<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">x</a>
  <a class="navbar-brand" href="{% url 'home' %}">
    <img src="{% static 'givers/img/car1.jpg' %}" width="30" height="30" class="d-inline-block align-top">
   <span>Giveaway</span>
</a>
  <a href="{% url 'blog:all_blogs' %}">Blog</a>
  {% if user.is_authenticated %}
  <a href="{% url 'creategift' %}">Offer Gift</a>
  <a href="{% url 'giveaway' %}">Gifts</a>
  <a href="{% url 'account_update' %}">Account Settings</a>
  <a href="#">How it Works</a>
  <a href="{% url 'contact' %}">Contact us</a>
  <a href="{% url 'logoutuser' %}">Logout</a>
  {% else %}
  <a href="#">How it Works</a>
  <a href="{% url 'contact' %}">Contact us</a>
  {% endif %}
</div>

<div id="main">
  <button class="openbtn" onclick="openNav()">☰ Menu</button>  
</div>
{% block content %}{% endblock %}
<script>
function openNav() {
  document.getElementById("mySidebar").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidebar").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>
   
</body>
<div class="row" style="padding-top: 30px;">
<div class="col-md-12 text-center">
                            
                                
    <a href="#"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
    <a href="#"><i class="fab fa-google-plus"></i></a>
    <a href="#"><i class="fab fa-youtube"></i></a>
    <a href="#"><i class="fa fa-rss"></i></a>
    <p style="font-size: 13px;color:black;font-weight: 100;font-family:monospace;">Copyright 2021 Giveaway</p>
</div>
</div>
</html> 

givers/templates/givers/contact.html
{% extends 'givers/base.html' %}
{% load static %}

{% load crispy_forms_tags %}



{% block content %}
{% include 'givers/message.html' %}


<div class="tdstyle">
<h1 style="text-align: center;border-bottom: thick double turquoise;">Contact Us</h1>
<p style="text-align: center;">kindly let us know how we can be of help</p>
<br>
<br>
<div class="row d-flex justify-content-center" style="padding-top: 30px;">
<form class="form-width" style="max-width: 18rem;border:slategray 2px solid;padding: 50px;border-radius: 15px;background-color: white;"  method ='POST' action="{% url 'contact' %}">
    {% csrf_token %}
    {{ form | crispy }}
    <button class="button button1" type='submit' style='background-color:aqua;'>Submit</button>
</form>
</div>
</div>


{% endblock %}

givers/templates/givers/creategiving.html
{% extends 'givers/base.html'  %}

{% load crispy_forms_tags %}


{% block content %}
{% include 'givers/message.html' %}
<div class="account">
<div class="container">
    <h1 style="text-align: center;font-weight: bolder;padding-top: 20px;">Create Gift</h1>
    <br>

    {{ error }}
    <br>
    <div class="row d-flex justify-content-center">
    <form class="form-width" enctype="multipart/form-data" style="max-width: 18rem;border:slategray 2px solid;padding: 50px;border-radius: 15px;background-color: white;" method ='POST',action="{% url 'signupuser' %}">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="button button1"   type='submit' style='background-color:aqua;'>Gift</button>
    </form>
    </div>
</div>
</div>









{% endblock %}

givers/templates/givers/giftpage.html
{% extends 'givers/base.html' %}

{% block content %}
<div class="top">
<div class="search-container">
<form action="{% url 'giveaway'  %}" method="get">
    <input name="q" type="text" placeholder="Search...">
    <button type="submit"><i class="fas fa-search"></i></button>
</form>
</div>
</div>



{% if page_obj.object_list %}
<h3 style ='text-align: center;font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;'>Gifts up For Grabs</h3>

<div class="container-fluid">
    {% for i in page_obj.object_list %}
    {% if forloop.counter0|divisibleby:4 %}<div class="row projects-holder">{% endif %} 
        
            <div class="col-md-3 col-sm-6">
                <div class="project-item">
                    <img style="border-radius: 12px;" src="{{ i.image.url }}" alt="pic" height="150" width="150">
                    <div class="project-hover">
                        <div class="inside">
                            <h5><a href="#">{{ i.name }}</a></h5>
                            <p>  {{ i.category }}---({{ i.quantity }})</p>
                        </div>
                    </div>
                </div>    
                
                    <div class="menu">
                        <form method="POST" action="{% url 'selectgift' i.id %}">
                            {% csrf_token %}
                            <button class="button button1"   type="submit">Pickup</button>
                        </form>
                    </div>
                
            </div>  
        {% if forloop.counter|divisibleby:4 or forloop.last %} </div>{% endif %} 
    {% endfor %}       
              
</div>
    {% else %}  
    <h4 style="text-align: center;padding-top: 20px;">No Available Gift in your State of Residence</h4>
</div> 
{% endif %}
<div class="row" style="padding-top: 10px;">
    <div class="col-md-5"></div>
    <div class="col-md-2" style="text-align: center;">
        {% if page_obj.object_list %}
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}"><<</a>
        {% endif %}
        <span>{{ page_obj.number }}</span>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">>></a>
        {% endif %}
        {% endif %}
    </div>
    <div class="col-md-5"></div>
</div>

{% endblock %}

givers/templates/givers/loginuser.html
{% extends 'givers/base.html'  %}

{% load crispy_forms_tags %}
{% load socialaccount %}

{% block content %}
{% include 'givers/message.html' %}

<h1 style='text-align: center;font-weight: bolder;'>Login here</h1>
<h2 style='text-align: center;'>{{ error }}</h2>
<br>
<div class="row d-flex justify-content-center">
<div class="col-md-8 mx-auto social-container my-2 order-md-1">
    <ul>
        <li>
    
            <button id='ig-color' class="btn mb-2 social-text">
                <i class="fab fa-instagram"></i><a href="#">Login with Instagram</a>
            </button>
        </li>
        <li>
            <button id='fb-color' class="btn mb-2 social-text">
                <i class="fab fa-facebook-f"></i><a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>
            </button>
        </li>
        <li>
            <button id='ld-color' class="btn mb-2 social-text">
                <i class="fab fa-google"></i><a href="{% provider_login_url 'google' %}">Login with Google</a>
            </button>
        </li>
    </ul>
</div>
</div>

<div class="separator">OR</div>
<div class="row d-flex justify-content-center">
<form class="form-width", method='POST',action="{% url 'loginuser' %}">
    <table>
        {% csrf_token %}
        {{ form | crispy }}
    </table>
    <!-- reCAPTCHA input -->
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <input type="hidden" id="g-recaptcha-response" name="g-recaptcha-response"> 
    <button class="button button1"  type='submit' >Login</button><span style="padding-left: 40px;"><a href="{% url 'signupuser' %}">New user? Signup</a></span>
    <a href="{% url 'password_reset' %}">Forgot Password?</a>  
</form>
</div>

{% endblock %}

givers/templates/givers/message.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}

givers/templates/givers/test.html
<h1>TESTING</h1>
{% for i in gift_list %}
<p>{{i}}</p>
{% endfor %}

givers/templates/givers/viewgift.html
{% extends 'givers/base.html' %}


{%  block content %}

{% load crispy_forms_tags %}
<div class="accstyle">
<h3 style="padding-left: 30px;">kindly review your {{ view.name }} gift </h3>
<hr>
<form class="form-width" style="padding-left: 40px;" method="POST",action="{% url 'creategift' %}">
    {% csrf_token %}
    <table>
        {{ form | crispy }}
    </table>
    <button class="button button2"  type="submit">submit</button>
</form>

<form method="POST" style="padding-left: 40px;"   action="{% url 'deletegift' view.id  %}">
    {% csrf_token %}
    <button class="button button4"   type="submit">delete</button>
</form>
</div>
{% endblock %}

givers/templates/givers/viewpicked.html
{% extends 'givers/base.html' %}


{%  block content %}

{% load crispy_forms_tags %}

<div class="accstyle">
<h3 style="padding-left: 30px;">kindly review your {{ pick.name }} gift </h3>
<hr>
<form class="form-width" style="padding-left: 40px;" method="POST" action="{% url 'redeempicked' picked.id  %}">
    {% csrf_token %}
    <table>
        {{ form | crispy }}
    </table>
    <div style="padding-left: 15px;">
    
    <button class="button button2" ><a href="{% url 'redeempicked' picked.id  %}">redeem</a></button>
    <button class="button button3"   type="submit" value='Return' name='return'>Return</button>
    <button class="button button4"   type="submit" value='Mark' name='mark'>Mark as Received</button>
    </div>
</form>
</div>
{% endblock %}